import turtle

def windows(south,north,east,west):
	turtle.home()
	turtle.showturtle()
	turtle.fillcolor("white")
	turtle.pencolor("white")
	turtle.up()
	turtle.left(90)
	turtle.forward(65)
	turtle.right(90)
	turtle.forward(35)
	
	turtle.down()			#window one
	turtle.begin_fill()
	turtle.forward(5)
	turtle.right(90)
	turtle.forward(5)
	turtle.right(90)
	turtle.forward(5)
	turtle.right(90)
	turtle.forward(5)
	turtle.right(90)
	turtle.end_fill()
	turtle.hideturtle()
	turtle.up()

	turtle.setheading(south)
	turtle.forward(10)
	
	turtle.down()			#window two
	turtle.begin_fill()
	turtle.forward(5)
	turtle.left(90)
	turtle.forward(5)
	turtle.left(90)
	turtle.forward(5)
	turtle.left(90)
	turtle.forward(5)
	turtle.left(90)
	turtle.end_fill()
	turtle.hideturtle()
	turtle.up()
	
	turtle.setheading(east)
	turtle.showturtle()
	turtle.forward(25)
	turtle.setheading(north)
	turtle.forward(70)
	turtle.setheading(east)
	
	turtle.down()			#window three
	turtle.begin_fill()
	turtle.forward(5)
	turtle.right(90)
	turtle.forward(5)
	turtle.right(90)
	turtle.forward(5)
	turtle.right(90)
	turtle.forward(5)
	turtle.right(90)
	turtle.end_fill()
	turtle.hideturtle()
	turtle.up()

	turtle.setheading(south)
	turtle.forward(10)
	
	turtle.down()			#window four
	turtle.begin_fill()
	turtle.forward(5)
	turtle.left(90)
	turtle.forward(5)
	turtle.left(90)
	turtle.forward(5)
	turtle.left(90)
	turtle.forward(5)
	turtle.left(90)
	turtle.end_fill()
	turtle.hideturtle()
	turtle.up()
	
	turtle.setheading(south)
	turtle.showturtle()
	turtle.forward(20)
	turtle.setheading(east)
	turtle.forward(25)
	turtle.setheading(east)
	
	turtle.down()			#window five
	turtle.begin_fill()
	turtle.forward(5)
	turtle.right(90)
	turtle.forward(5)
	turtle.right(90)
	turtle.forward(5)
	turtle.right(90)
	turtle.forward(5)
	turtle.right(90)
	turtle.end_fill()
	turtle.hideturtle()
	turtle.up()
	
	turtle.setheading(east)
	turtle.showturtle()
	turtle.forward(45)
	
	turtle.down()			#window six
	turtle.begin_fill()
	turtle.forward(5)
	turtle.right(90)
	turtle.forward(5)
	turtle.right(90)
	turtle.forward(5)
	turtle.right(90)
	turtle.forward(5)
	turtle.right(90)
	turtle.end_fill()
	turtle.hideturtle()
	turtle.up()
	
	turtle.setheading(south)
	turtle.forward(60)
	turtle.setheading(west)
	turtle.forward(50)
	
	turtle.down()			#window seven
	turtle.setheading(east)
	turtle.begin_fill()
	turtle.forward(5)
	turtle.right(90)
	turtle.forward(5)
	turtle.right(90)
	turtle.forward(5)
	turtle.right(90)
	turtle.forward(5)
	turtle.right(90)
	turtle.end_fill()
	turtle.hideturtle()
	turtle.up()
